/*----- PROTECTED REGION ID(Pico14StateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        Pico14StateMachine.cpp
//
// description : State machine file for the Pico14 class
//
// project :     Pico14
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <Pico14.h>

/*----- PROTECTED REGION END -----*/	//	Pico14::Pico14StateMachine.cpp

//================================================================
//  States   |  Description
//================================================================
//  ON       |  
//  OFF      |  
//  FAULT    |  
//  RUNNING  |  


namespace Pico14_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : Pico14::is_chanAstream_allowed()
 *	Description : Execution allowed for chanAstream attribute
 */
//--------------------------------------------------------
bool Pico14::is_chanAstream_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for chanAstream attribute in read access.
	/*----- PROTECTED REGION ID(Pico14::chanAstreamStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Pico14::chanAstreamStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Pico14::is_chanA_allowed()
 *	Description : Execution allowed for chanA attribute
 */
//--------------------------------------------------------
bool Pico14::is_chanA_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for chanA attribute in read access.
	/*----- PROTECTED REGION ID(Pico14::chanAStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Pico14::chanAStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Pico14::is_chanB_allowed()
 *	Description : Execution allowed for chanB attribute
 */
//--------------------------------------------------------
bool Pico14::is_chanB_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for chanB attribute in read access.
	/*----- PROTECTED REGION ID(Pico14::chanBStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Pico14::chanBStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : Pico14::is_On_allowed()
 *	Description : Execution allowed for On attribute
 */
//--------------------------------------------------------
bool Pico14::is_On_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::ON ||
		get_state()==Tango::FAULT ||
		get_state()==Tango::RUNNING)
	{
	/*----- PROTECTED REGION ID(Pico14::OnStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Pico14::OnStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Pico14::is_Off_allowed()
 *	Description : Execution allowed for Off attribute
 */
//--------------------------------------------------------
bool Pico14::is_Off_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF ||
		get_state()==Tango::FAULT ||
		get_state()==Tango::RUNNING)
	{
	/*----- PROTECTED REGION ID(Pico14::OffStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Pico14::OffStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Pico14::is_SetDefaults_allowed()
 *	Description : Execution allowed for SetDefaults attribute
 */
//--------------------------------------------------------
bool Pico14::is_SetDefaults_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF ||
		get_state()==Tango::FAULT ||
		get_state()==Tango::RUNNING)
	{
	/*----- PROTECTED REGION ID(Pico14::SetDefaultsStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Pico14::SetDefaultsStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Pico14::is_StartStreaming_allowed()
 *	Description : Execution allowed for StartStreaming attribute
 */
//--------------------------------------------------------
bool Pico14::is_StartStreaming_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF ||
		get_state()==Tango::FAULT ||
		get_state()==Tango::RUNNING)
	{
	/*----- PROTECTED REGION ID(Pico14::StartStreamingStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Pico14::StartStreamingStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Pico14::is_StopStreaming_allowed()
 *	Description : Execution allowed for StopStreaming attribute
 */
//--------------------------------------------------------
bool Pico14::is_StopStreaming_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF ||
		get_state()==Tango::FAULT)
	{
	/*----- PROTECTED REGION ID(Pico14::StopStreamingStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Pico14::StopStreamingStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Pico14::is_CollectBlock_allowed()
 *	Description : Execution allowed for CollectBlock attribute
 */
//--------------------------------------------------------
bool Pico14::is_CollectBlock_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF ||
		get_state()==Tango::FAULT ||
		get_state()==Tango::RUNNING)
	{
	/*----- PROTECTED REGION ID(Pico14::CollectBlockStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Pico14::CollectBlockStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Pico14::is_Update_allowed()
 *	Description : Execution allowed for Update attribute
 */
//--------------------------------------------------------
bool Pico14::is_Update_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::ON ||
		get_state()==Tango::OFF ||
		get_state()==Tango::FAULT ||
		get_state()==Tango::RUNNING)
	{
	/*----- PROTECTED REGION ID(Pico14::UpdateStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Pico14::UpdateStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Pico14::is_Update_new_allowed()
 *	Description : Execution allowed for Update_new attribute
 */
//--------------------------------------------------------
bool Pico14::is_Update_new_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Update_new command.
	/*----- PROTECTED REGION ID(Pico14::Update_newStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Pico14::Update_newStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(Pico14::Pico14StateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	Pico14::Pico14StateAllowed.AdditionalMethods

}	//	End of namespace
